### ISSUE TITLE
Feature Request: Multiple passwords for specific pages of the website

### ISSUE THREAD

**Issue by saschabregenhorn** [Pechente/kirby-password-guard#1]
Hey,

thanks for the plugin, super cool, exactly what I need right now!

You already support patterns in the config, would be cool I we could have multiple passwords with corresponding patterns. 

THX
Sascha

**Comment by Pechente** [comment]
Hey! That's a good suggestions and I considered implementing a feature like this when I started making the plugin. However, I'd like to keep the plugin simple and I feel like this would add unneeded complexity, especially when it comes to the configuration.

Did you check out this plugin yet? https://plugins.getkirby.com/johannschopplich/locked-pages It sounds like it might be more fitting for your use case.

**Comment by saschabregenhorn** [comment]
Oh, ok, I didn't know that one, will look into it. Thanks for the quick response!

**Comment by Pechente** [comment]
@saschabregenhorn Just checking in. Did the other plugin cover this use case? Otherwise I will leave this issue open to be implemented in the future.

**Comment by saschabregenhorn** [comment]
> Just checking in. Did the other plugin cover this use case? Otherwise I will leave this issue open to be implemented in the future.

Sorry, not yet. Waiting for infos from the client. I'll get back to you!

**Comment by saschabregenhorn** [comment]
> Just checking in. Did the other plugin cover this use case? Otherwise I will leave this issue open to be implemented in the future.

Hey, I've checked the Kirby Locked Pages plugin. The main problem is that it protects single pages, not the subpages of that page. 

However, luckily my client changed his mind and wants only one password for the whole site. So I am using your plugin now, works like a charm. Thanks!

**Comment by Pechente** [comment]
Perfect! I'm closing this for now and if anyone else has demand for this or a similar feature, they can just reopen it.
